project:
  type: website
  render:
    - index.qmd
    - reports/data_pipeline.qmd
    - reports/metadata_pipeline.qmd
    - reports/metadata_EDA.qmd
    - reports/clr.qmd
    - reports/pca.qmd
    - reports/mofa.qmd
    - reports/umap.qmd
    - reports/mofa_pca_analysis.qmd
    - reports/clustering_execution.qmd
    - reports/clustering_analysis.qmd
    - reports/pareto_analysis.qmd
    - reports/prediction_analysis.qmd
  output-dir: docs

website:
  title: "Integraci√≥n omica oceano Chile"

format:
  html:
    embed-resources: true  
    fig-format: svg

execute:
  kernel: Omic_Integration

